### ISSUE TITLE
v1.0.6 packaged incorrectly

### ISSUE THREAD

**Issue by radicand** [dharness/react-chat-window#65]
When installing 1.0.6 from npm, the package is missing lib/ es/ etc. If I downgrade to 1.0.5 they re-appear.

I haven't cloned your repo to test for why this is the case, but something in your build/publish phase may be off.

**Comment by dharness** [comment]
Thanks! I released that on the fly the other day and must have missed something. I'll look into it tonight.

**Comment by mattmezza** [comment]
you can find a recent version integrated here https://github.com/mattmezza/react-chat-window patch your `package.json` `yarn add mattmezza/react-chat-window` while waiting for the new release if you wanna try out the new features. I had to manually add the missing files `yarn build --copy-files` then push them to the remote repo and then patch the `package.json` file.

**Comment by dharness** [comment]
Re-release 1.0.7. Should be good now, sorry about that.

**Comment by radicand** [comment]
thanks for the quick turnaround -- it looks like the css files are still missing though in this release (though the JS files are present).
